name: CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'lib/**'
      - 'test/**'
      - '.github/workflows/ci.yml'

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.1398+cb5635714

      - name: Build and run project
        run: zig build run

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.1398+cb5635714

      - name: Run tests
        run: zig build test
